const ProjectList = [
  {
    id: 1,
    name: "InfluenceNet",
    tags: ["Flask", "Flask-SQLAlchemy", "Flask-Restful"],
    github_url:
      "https://github.com/23f2001281/Influencer-Sponsorship-System-v1-MAD-1",
    owner: "23f2001281",
    repo: "Influencer-Sponsorship-System-v1-MAD-1",
    description:
      "A platform to connect sponsors with influencers so that sponsors can get their products/services advertised and influencers can get monetary benefits.",
    points: [
      "Designed a role-based dashboard for streamlined campaign and ad request management.",
      "Implemented a dynamic ad request system with renegotiation capabilities.",
      "Developed search, filter, and analytics features for improved user insights.",
      "Created optimized RESTful API endpoints with secure authentication.",
    ],
    image: null,
    video: null,
    deployed_url: null,
  },
  {
    id: 2,
    name: "Zoom Trip - 3D Globe Explorer",
    tags: ["React", "Cesium", "Gemini AI"],
    github_url: "https://github.com/ayushptl1810/codecircuit",
    owner: "ayushptl1810",
    repo: "codecircuit",
    description:
      "A modern web application that helps users discover and explore places around the world using an interactive 3D globe visualization. ",
    points: [
      "Built an interactive 3D globe application to help users explore global destinations using CesiumJS, React and Gemini AI for intelligent place suggestions based on user preferences and activity types.",
      "Implemented real-time visualization with smooth camera transitions, animated globe interactions, and instant location highlighting.",
      "Developed dynamic filtering and search capabilities, allowing users to refine results with contextual filters per activity type.",
    ],
    image: null,
    video: null,
    deployed_url: "https://codecircuit-one.vercel.app/",
  },
  {
    id: 3,
    name: "Quiz Master App",
    tags: ["VueJs", "ChartJs", "Redux", "Celery", "Flask", "Flask-SQLAlchemy"],
    github_url: "https://github.com/23f2001281/Quiz-Master-App-V2",
    owner: "23f2001281",
    repo: "Quiz-Master-App-V2",
    description:
      "A comprehensive web-based quiz management system with real-time quiz taking, automated reporting, personalized summary generation and administrative controls.",
    points: [
      "Designed a role-based dashboard for students and administrators with secure JWT authentication.",
      "Implemented real-time quiz workflows with timer functionality, answer tracking, and instant scoring.",
      "Built content management tools for subjects, chapters, quizzes, and student records.",
      "Developed automated reporting and analytics with Celery background tasks and interactive Chart.js dashboards.",
    ],
    image: null,
    video: null,
    deployed_url: null,
  },
  {
    id: 4,
    name: "Itinary Generator",
    tags: [
      "NextJs",
      "TailwindCSS",
      "Cesium",
      "CrewAI",
      "LangChain",
      "Pydantic",
      "FastAPI",
    ],
    github_url: "https://github.com/JayGuri/Codeshastra_XI_PUJA",
    owner: "JayGuri",
    repo: "Codeshastra_XI_PUJA",
    description:
      "An innovative travel planning platform that combines immersive 3D visualization with AI-powered itinerary generation.",
    points: [
      "Developed the Community feature, enabling interactive user engagement through a dedicated platform for discussions and content sharing.",
      "Implemented the Scrapbook component, allowing users to post and share memorable events.",
      "Debugged critical issues on the home page, enhancing load speed and user experience.",
    ],
    image: null,
    video: null,
    deployed_url: null,
  },
  {
    id: 5,
    name: "StackIt - Community Q&A Forum",
    tags: ["NextJs", "TailwindCSS", "SocketIO", "JWT", "Express"],
    github_url: "https://github.com/HarshilForWork/Odoo_JBBR",
    owner: "HarshilForWork",
    repo: "Odoo_JBBR",
    description:
      "A modern, feature-rich Q&A forum for asking questions, sharing knowledge, and building a community around knowledge exchange.",
    points: [
      "Designed a role-based Q&A platform with secure JWT authentication, user profiles, and rich content editor supporting images, tags, and edit tracking.",
      "Implemented real-time updates and notifications via Socket.IO for answers, votes, and content interactions.",
      "Built an admin dashboard for user management, content moderation, analytics, and global announcements.",
      "Integrated search, filtering, and pagination workflows for efficient content discovery and seamless user experience.",
    ],
    image: null,
    video: null,
    deployed_url: null,
  },
  {
    id: 6,
    name: "Zentry Clone",
    tags: ["HTML", "CSS", "JavaScript"],
    github_url: "https://github.com/ayushptl1810/zentryclone",
    owner: "ayushptl1810",
    repo: "zentryclone",
    description:
      "A responsive and animated landing page for Zentry, a gaming platform",
    points: [
      "Developed a basic clone of Zentry.com, replicating core UI components and layout.",
      "Implemented multiple animations using pure CSS, enhancing user experience with smooth transitions and effects.",
      "A clean, dark-themed design with a focus on user experience.",
    ],
    image: null,
    video: null,
    deployed_url: "https://zentryclone-one.vercel.app/",
  },
  {
    id: 7,
    name: "Padre Gino's Pizzeria",
    tags: ["React", "TanStack Router", "Tanstack Query", "TailwindCSS"],
    github_url: "https://github.com/ayushptl1810/PadreGino",
    owner: "ayushptl1810",
    repo: "PadreGino",
    description:
      "A modern web app for Padre Gino's Pizzeria, offering a smooth experience to browse the menu, place orders, and track past purchases.",
    points: [
      "Developed a Feature-Rich Single-Page Application (SPA): Engineered the PadreGino project using React's component-based architecture and modern ES6+ features, ensuring a seamless and interactive user experience.",
      "Implemented Reusable and Scalable UI Components: Built modular components with React Hooks for state and lifecycle management, which improved code maintainability and accelerated development.",
      "Enhanced Client-Side Routing and State Management: Leveraged libraries (such as react-router for navigation) and effective state management techniques to optimize the flow and responsiveness of the application.",
    ],
    image: null,
    video: null,
    deployed_url: null,
  },
  {
    id: 8,
    name: "Virtual Teaching Assistant",
    tags: ["FastAPI", "Pinecone", "BS4", "Playwright"],
    github_url: "https://github.com/ayushptl1810/TDS-PROJECT-1",
    owner: "ayushptl1810",
    repo: "TDS-PROJECT-1",
    description:
      "A virtual teaching assistant for the Tools in Data Science (TDS) course at IIT Madras, powered by Pinecone vector search and Google's Gemini AI.",
    points: [
      "Built Robust Web and Forum Scrapers: Extracted structured content and metadata from both Markdown course files and Discourse forums, ensuring seamless integration and high-quality downstream data processing.",
      "Deployed Scalable Vector Search Infrastructure: Deployed scalable vector search infrastructure using Pinecone and LLaMA v2 embeddings after migrating from FAISS and Sentence Transformers, with optimized batch upserts, rate-limit handling, and metadata-aware indexing for efficient, large-scale semantic search.",
      "Implemented Adaptive, TF-IDF-Driven Search Logic: Developed a hybrid search algorithm that dynamically learns keyword weights, chunks and ranks context intelligently, and fuses course and forum content to return rich, relevant results, which are then passed to Gemini AI for final answer generation.",
    ],
    image: null,
    video: null,
    deployed_url: "https://tds-project-1-ujvv.onrender.com",
  },
  {
    id: 9,
    name: "Data Analyst Agent",
    tags: [
      "FastAPI",
      "LangChain",
      "CrewAI",
      "Pydantic",
      "Pinecone",
      "Mammoth",
      "PyMuPDF",
      "PDFPlumber",
      "BS4",
      "Playwright",
    ],
    github_url: "https://github.com/23f2001281/Data-Analyst-Agent",
    owner: "23f2001281",
    repo: "Data-Analyst-Agent",
    description:
      "An AI-powered Data Analyst Agent that connects to diverse data sources, performs advanced analysis, and delivers valuable insights from databases, PDFs, or the web.",
    points: [
      "Built an AI-powered Data Analyst Agent with CrewAI, FastAPI, and LangChain to analyze SQL databases, PDFs, and web data through natural language queries.",
      "Implemented semantic search with Pinecone vector embeddings and ONNX-optimized All-MiniLM-L6-v2 model for efficient document retrieval and intelligent chunking.",
      "Developed data visualization and analysis workflows using pandas and chart generation for trend detection and actionable insights.",
      "Integrated web scraping, PDF parsing, and REST API endpoints, enabling seamless data ingestion, interaction, and integration with external applications.",
    ],
    image: null,
    video: null,
    deployed_url: null,
  },
];

export default ProjectList;
